print("Welcome to the learning of machine learning using python.\n")
print("We will learn:")
print("(1) Python Fundamentals")
print("(2) Machine Learning")
print("(3) Deep Learning")
print("(4) Unsupervised Learning")
